analytics: {}
color:
  brandColors:
    - '#E0C0D8'
    - '#180820'
    - '#8060B0'
    - '#8038A8'
    - '#A868B8'
  brandStrength: 0
  lightness: 0
  rhythmicContrast: 0
  saturation: 0
cta: {}
layout_spectrum: 0.293918
name: teojianrong
opengraph: {}
purpose: {}
typography_spectrum: 0.351351
